jobs:
  load_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install k6 CLI
        run: |
          curl -s https://packagecloud.io/install/repositories/grafana/stable/script.deb.sh | sudo bash
          sudo apt-get install -y k6

      - name: Run k6 load test
        run: k6 run tests/load.js
