name: Run k6 Load Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6 manually (v0.49.0)
        run: |
          sudo apt-get update && sudo apt-get install -y curl unzip
          wget https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.zip
          unzip k6-v0.49.0-linux-amd64.zip
          sudo mv k6-v0.49.0-linux-amd64/k6 /usr/local/bin/
          k6 version

      - name: Run load test
        run: k6 run tests/load.js
